name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: affordable_housing_monitoring
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: affordable_housing_monitoring_test
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: |
        sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn install
    - name: Setup database and run tests
      run: |
        cp config/database.ci.yml config/database.yml
        bundle exec rake db:create db:migrate
        bundle exec rspec
      env:
        PGHOST: localhost
        POSTGRES_DB: affordable_housing_monitoring_test
        POSTGRES_USER: affordable_housing_monitoring
        POSTGRES_PASSWORD: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
