name: CI

on: [push]

jobs:
  ci:

    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:17@sha256:5b96f1a16bd9768b060dd2ffe55cb6225c4d9ef4d214a8b21eb08134869a97e4
        env:
          POSTGRES_USER: affordable_housing_monitoring
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: affordable_housing_monitoring_test
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22
    - name: Install dependencies
      run: |
        yarn install
    - name: Set up database and run tests
      run: |
        cp config/database.ci.yml config/database.yml
        bundle exec rake db:create db:migrate
        bundle exec rspec
      env:
        PGHOST: localhost
        POSTGRES_DB: affordable_housing_monitoring_test
        POSTGRES_USER: affordable_housing_monitoring
        POSTGRES_PASSWORD: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
